### ISSUE TITLE
提示程序异常，请问是什么导致的？

### ISSUE THREAD

**Issue by orjf** [goodmangll/falco-docker#2]
资源挂载在115，用户绑定在阿里云盘，帮忙看看什么原因导致的，邮箱：46417778@qq.com     万分感谢
错误：
[31m[2024-06-13 18:18:24] [error] - 	程序异常。Unhandled promise rejection: Cannot read properties of undefined (reading 'includes')[0m
[31m[2024-06-13 18:18:24] [error] - 	TypeError: Cannot read properties of undefined (reading 'includes')
    at Server.fillPlayInfo (/user/src/app/src/server/index.js:1:10326)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0x2f04f3 (/user/src/app/src/server/index.js:1:9904)[0m
[31m[2024-06-13 18:18:24] [error] - 	程序异常。Unhandled promise rejection: Cannot read properties of undefined (reading 'includes')[0m
[31m[2024-06-13 18:18:24] [error] - 	TypeError: Cannot read properties of undefined (reading 'includes')
    at Server.fillPlayInfo (/user/src/app/src/server/index.js:1:10326)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0x2f04f3 (/user/src/app/src/server/index.js:1:9904)[0m

**Comment by orjf** [comment]
您的邮件已收到
