### ISSUE TITLE
很好的应用，求更新

### ISSUE THREAD

**Issue by huangzlin9** [goodmangll/falco-docker#9]
日志显示error：115需要携带UserAgent，实测是可以播放的
如果能够再快点就爽了

**Comment by xiedakai** [comment]
@goodmangll  我也遇到这个报错了

[2024-11-29 16:57:58]: error: Error: 115需要携带UserAgent才能获取直连！ at /user/src/app/src/server/index.js:1:6256 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async serve (/user/src/app/node_modules/.store/koa-static@5.0.0/node_modules/koa-static/index.js:53:9) at async cors (/user/src/app/node_modules/.store/koa2-cors@2.0.6/node_modules/koa2-cors/dist/index.js:91:9) at async /user/src/app/src/server/index.js:1:5368 at async /user/src/app/src/server/index.js:1:5247 at async bodyParser (/user/src/app/node_modules/.store/koa-bodyparser@4.4.1/node_modules/koa-bodyparser/index.js:78:5)

**Comment by huangzlin9** [comment]
大佬更新吧
